import "./globals.css";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kerim-Test-Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full`}>
        <Navbar />

        <main className="h-full flex flex-1 flex-grow bg-zinc-100">
          {children}
        </main>
      </body>
    </html>
  );
}
